### ISSUE TITLE
[Feat] : MainView #2

### ISSUE THREAD

**Issue by Juhwa-Lee1023** [PLREQ/Muzip#5]
## Description
- MainView #2

## Tasks
 - [ ] Reusable Music List View Cell
 - [ ] Reusable Album List View Cell
 - [ ] Switch List Mode
